language: csharp
solution: "WordOfTheDay.sln"
mono:
  - latest
  install:
    - nuget restore "WordOfTheDay.sln"
      - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
      script:
        - xbuild /p:Configuration=Test "WordOfTheDay.sln"
	  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe "./WordOfTheDayTests/bin/Release/WordOfTheDayTests.dll"