language: csharp
solution: WordOfTheDay.sln
mono:
  - latest
install:
  - nuget restore WordOfTheDay.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  - sudo apt-get install nunit-console
  - sudo apt-get install gtk-sharp2
  - curl -sS https://api.nuget.org/packages/mono.cecil.0.9.5.4.nupkg > /tmp/mono.cecil.0.9.5.4.nupkg.zip
  - unzip /tmp/mono.cecil.0.9.5.4.nupkg.zip -d /tmp/cecil
  - cp /tmp/cecil/lib/net40/Mono.Cecil.dll .
  - cp /tmp/cecil/lib/net40/Mono.Cecil.dll /tmp/cecil/
  - git clone --depth=50 git://github.com/csMACnz/monocov.git ../../csMACnz/monocov
  - cd ../../csMACnz/monocov
  - cp /tmp/cecil/Mono.Cecil.dll .
  - ./configure
  - make
  - sudo make install
  - cd ../../tvand7093/WordOfTheDay
script:
  - xbuild /p:Configuration=Test WordOfTheDay.sln
  - export LD_LIBRARY_PATH=/usr/local/lib
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe "./WordOfTheDayTests/bin/Test/WordOfTheDayTests.dll"
  - mono --debug --profile=monocov:outfile=monocovCoverage.cov,+WordOfTheDay ./packages/NUnit.Console.3.0.0-alpha-5b/tools/nunit-console.exe --process=Single ./WordOfTheDay/WordOfTheDayTests/bin/Test/WordOfTheDayTests.dll
  - monocov --export-xml=monocovCoverage monocovCoverage.cov
  - cat monocovCoverage.cov
  - ls monocovCoverage
  - REPO_COMMIT_AUTHOR=$(git show -s --pretty=format:"%cn")
  - REPO_COMMIT_AUTHOR_EMAIL=$(git show -s --pretty=format:"%ce")
  - REPO_COMMIT_MESSAGE=$(git show -s --pretty=format:"%s")
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_BRANCH
  - echo $REPO_COMMIT_AUTHOR
  - echo $REPO_COMMIT_AUTHOR_EMAIL
  - echo $REPO_COMMIT_MESSAGE
  - echo $TRAVIS_JOB_ID
  - mono ./packages/coveralls.net.0.5.0/csmacnz.Coveralls.exe --monocov -i ./monocovCoverage --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitAuthor "$REPO_COMMIT_AUTHOR" --commitEmail "$REPO_COMMIT_AUTHOR_EMAIL" --commitMessage "$REPO_COMMIT_MESSAGE" --jobId $TRAVIS_JOB_ID --serviceName travis-ci --useRelativePaths